# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}


  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST}:${NACOS_PORT}
        username: ${NACOS_USERNAME}
        password: ${NACOS_PASSWORD}
        enabled: true
        register-enabled: true
      config:
        enabled: false
        import-check:
          enabled: false

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  # Elasticsearch 配置
  elasticsearch:
    uris: ${ES_HOST}:${ES_PORT}
    connection-timeout: 5000
    socket-timeout: 30000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# SpringDoc 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: true
  packages-to-scan: com.huizuike.flashdeliverjava.controller

# JWT 配置
jwt:
  secret: flash-delivery-secret-key-2026-spring-boot-3-5-14-jwt
  access-expiration: 1800     # Access Token 30 分钟
  refresh-expiration: 604800  # Refresh Token 7 天

snowflake:
  worker-id: 1  # 分库分表时，每个实例设置不同的值

logging:
  level:
    root: INFO
    org.springframework.data.redis: DEBUG
    com.flash.delivery: DEBUG
#    org.springframework.data.elasticsearch: DEBUG
#    co.elastic.clients: DEBUG
#    org.elasticsearch.client: DEBUG